---
- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"
  tags: users

- name: create
  include:
    user_create.yml user={{ user_item }}
  with_items: '{{ users }}'
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:create

- name: create key directory
  file:
    path: "{{ users_ssh_key_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: users_ssh_key_path is not none

- name: ssh keys
  include:
    user_sshkey.yml user={{ user_item }}
  with_items: '{{ users }}'
  when: users_upload_ssh_keys
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:sshkey

- name: delete
  include:
    user_delete.yml user={{ user_item }}
  with_items: '{{ users_deleted }}'
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:delete
