---
- name: "Set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-{{ ansible_os_family }}.yml"
    - "os-default.yml"
  tags: always

- name: "Create users"
  ansible.builtin.include_tasks:
    file: user_create.yml
    apply:
      tags:
        - users
        - users:create
  vars:
    user: "{{ user_item }}"
  loop: '{{ users }}'
  loop_control:
    loop_var: user_item
  when: users_is_supported
  tags: always

- name: "Create key directory"
  ansible.builtin.file:
    path: "{{ users_ssh_key_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: users_is_supported and users_ssh_key_path is not none
  tags:
    - users
    - users:sshkey

- name: "Upload ssh keys"
  ansible.builtin.include_tasks:
    file: user_sshkey.yml
    apply:
      tags:
      - users
      - users:sshkey
  vars:
    user: "{{ user_item }}"
  loop: '{{ users }}'
  when: users_upload_ssh_keys
  loop_control:
    loop_var: user_item
  tags: always

- name: "Delete users"
  ansible.builtin.include_tasks:
    file: user_delete.yml
    apply:
      tags:
      - users
      - users:delete
  vars:
    user: "{{ user_item }}"
  loop: '{{ users_deleted }}'
  loop_control:
    loop_var: user_item
  when: users_is_supported
  tags: always
