---
# tasks file for users

- name: user group creation
  action: group 
    name="{{ item.username }}"
    gid="{{ item.uid if item.uid is defined else users_available[item.username]['uid']}}"
  with_items: users
  tags: users

- name: user creation
  action: 
    user
    name={{ item.username }}
    group={{ item.username }}
    groups="{{ item.groups|join(',') if item.groups is defined else users_available[item.username]['groups']|join(',') }}"
    shell="{{ item.shell if item.shell is defined else users_available[item.username]['shell'] }}"
    comment="{{ users_available[item.username]['name'] }}"
    uid="{{ item.uid if item.uid is defined else users_available[item.username]['uid'] }}"
    createhome=yes
    password="{{ item.password if item.password is defined else users_available[item.username]['password'] }}"
    update_password=on_create
  with_items: users
  tags: users

- name: creating .ssh directory
  action: file path=~{{ item.username }}/.ssh owner={{ item.username }} group={{ item.username }} state=directory mode=0750
  with_items: users
  tags: users

- name: uploading ssh keys
  action: copy src={{ users_dir_ssh_keys}}/{{ item.username }}.pub dest=~{{ item.username }}/.ssh/authorized_keys owner={{ item.username }} group={{ item.username }} mode=0640
  with_items: users
  tags: users

- name: user removal
  action: user name="{{ item.key }}" state=absent
  with_dict: "{{ users_available }}"
  when: "item.key not in {{ users|map(attribute='username')|list }}"
  tags: [users, del]

- name: group removal
  action: group name="{{ item.key }}" state=absent
  with_dict: "{{ users_available }}"
  when: "item.key not in {{ users|map(attribute='username')|list }}"
  tags: [users, del]
