---
- name: "Set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags: users

- name: "Create users"
  ansible.builtin.include_tasks:
    user_create.yml
  vars:
    user: "{{ user_item }}"
  loop: '{{ users }}'
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:create
  when: users_is_supported

- name: "Create key directory"
  ansible.builtin.file:
    path: "{{ users_ssh_key_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: users_is_supported and users_ssh_key_path is not none

- name: "Upload ssh keys"
  ansible.builtin.include_tasks:
    user_sshkey.yml
  vars:
    user: "{{ user_item }}"
  loop: '{{ users }}'
  when: users_upload_ssh_keys
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:sshkey
  when: users_is_supported

- name: "Delete users"
  ansible.builtin.include_tasks:
    user_delete.yml
  vars:
    user: "{{ user_item }}"
  loop: '{{ users_deleted }}'
  loop_control:
    loop_var: user_item
  tags:
    - users
    - users:delete
  when: users_is_supported
