---
- name: authorized keys (custom path)
  copy: 
    src: "{{ users_dir_ssh_keys }}/{{ user.username }}.pub"
    dest: "{{ users_ssh_key_path }}"
    owner: root
    group: root
    mode: 0644
  when: users_ssh_key_path is not none  

- name: authorized keys (home dir)
  authorized_key:
    user: "{{ user.username }}"
    state: present
    manage_dir: True
    key: "{{ key_item }}"
    exclusive: yes
  with_file:
    - "{{ users_dir_ssh_keys }}/{{ user.username }}.pub"
  loop_control:
    loop_var: key_item
  when: users_ssh_key_path is none
