---
- name: "User delete: {{ user.username }}"
  ansible.builtin.user:
    name: "{{ user.username }}"
    state: absent

- name: "Group delete: {{ user.username }}"
  ansible.builtin.group:
    name: "{{ user.username }}"
    state: absent
