---
- name: "User delete"
  ansible.builtin.user:
    name: "{{ user.username }}"
    state: absent
  tags:
    - users
    - users:delete

- name: "Group delete"
  ansible.builtin.group:
    name: "{{ user.username }}"
    state: absent
  tags:
    - users
    - users:delete
