---
- name: set user_data variable
  set_fact:
    user_data: "{{users_available[user.username]}}"

- name: user group creation
  group:
    name: "{{ user.username }}"
    gid: "{{ user.uid if user.uid is defined else user_data.uid if user_data.uid is defined else omit }}"
  when: users_create_user_group

- name: set user group fact 1
  set_fact:
    user_groups: "{{ user.groups|default(user_data.groups)|default([]) }}"

- name: set user group fact 2
  set_fact:
    user_groups: "{{ user_groups|union(users_admin_groups) }}"
  when: user.is_admin|default(user_data.is_admin)|default(False)

- name: user creation
  user:
    name: "{{ user.username }}"
    group: "{{ user.group|default(user_data.group)|default(user.username) }}"
    groups: "{{ user_groups|join(',') if user_groups|length else omit  }}"
    shell: "{{ user.shell|default(user_data.shell)|default(users_default_shell) }}"
    comment: "{{ user.comment|default(user_data.comment)|default(user_data.name)|default(omit) }}"
    uid: "{{ user.uid|default(user_data.uid)|default(omit) }}"
    createhome: yes
    password: "{{ user.password|default(user_data.password)|default(omit) }}"
    update_password: "{{ users_update_password }}"
  tags:
    - users
    - users:create

- name: is user admin
  user:
    name: "{{ user.username }}"
    groups: "{{ users_admin_groups|join(',') }}"
    append: yes
  when: user.is_admin|default(user_data.is_admin)|default(False)
